### ISSUE TITLE
Port behavior/configuration

### ISSUE THREAD

**Issue by FredKSchott** [lukejacksonn/servor#34] opened 2020-01-15 06:27 UTC
Spinoff of a convo here: https://github.com/pikapkg/snowpack/pull/145

I know that I'll commonly have to restart my dev server multiple times during development, just as I switch around different terminals and tasks and such. When the dev server switches ports on me, I have to go update any URLs in any open browser tabs, instead of just refreshing the page. There's something less confusing about it as well, to have less changing/moving parts.

Obviously you can configure the port, but the fact that I also need to know the two options that come before it makes that less simple. Putting those three options behind flags so that I could do something like `servor -p 1234`/`servor --port 1234` would be an improvement as well.
 
^ This is half personal opinion, and half me giving feedback based on writing the Snowpack docs and trying to keep things simple.

**Comment by lukejacksonn** [comment] 2020-01-15 16:11
Hey Fred 👋 thanks for the comments here and I totally understand where you are coming from. Personally I am conflicted internally here for the reasons:

- Currently all the flags are binary (on|off) which makes it both simple for the user to comprehend and simple to parse the command line arguments in the code (see [here](https://github.com/lukejacksonn/servor/blob/master/cli.js#L23)). Adding as you suggest `--port [argument]` although convenient breaks this pattern and personally I have never been a fan of mixing flagged parameter values with positional ones.
- The API has always been `servor <directory> <file> <port>` and that again was done for the sakes of simplicity both for the user and for the implementation. It was designed to be transparent (a WYSIWYG command) encapsulating the most common arguments in the order that they appear in the resultant URL.
- Choosing an available port instead of failing when no port is specified is especially useful when running multiple local servers at once. Which is something I personally do a lot and is why the feature was implemented; perhaps in contra to your workflow I rarely restart my dev servers!

Now.. I am not saying that these assumptions are by any means _correct_, nor that they would work for _all_ cases (evidently not 😅) but generally they work and I would like to stick to them if possible. That said you make a very good point about the default behaviour being somewhat confusing and I would like to help you (and others in a similar situation) out!

Off the top of my head I can think of one solution which might appease us both and that is to prioritise the port whereby servor would:

1. Use the port specified explicitly by the user in the position arguments (otherwise fail).
2. Try start on a default port (which would be specified in the docs, perhaps `8080` or `3000`) otherwise choose a random available port.

This way running `npx servor` would usually result in a server starting on port `8080` unless there was already running on that port in which case it would start anyway on a random available port; in both cases the port which was chosen would be logged out top the user anyway.

What are you thoughts on this solution and do you have any other suggestion given the conflicts of interest that I have listed above?

**Comment by FredKSchott** [comment] 2020-01-15 16:46
> Try start on a default port (which would be specified in the docs, perhaps 8080 or 3000) otherwise choose a random available port.

I like this behavior in other dev servers! The solution outlined here makes sense to me. I personally don't find the 3 implicit arguments as usable/user-friendly as moving them behind explicit CLI flags (I don't know the CLI by heart, so It's harder to parse and understand whats going on just by looking at it). But I understand your reasoning behind the current design outlined above and that makes sense to me. As we're both saying, this is all personal preference (and I'm far from a servor power user :)

But I love the fact that servor installs so fast. I'll probably change the Snowpack quickstart tutorial to use it eventually for this reason alone, but the random port is is the only thing holding me back as "might be confusing to users who try to run it twice".

**Comment by lukejacksonn** [comment] 2020-01-15 19:25
Makes sense! I have made a PR for this behaviour (here #35) and also added support for `process.env.PORT` along with a more graceful exit when the server can't be ran on a specified port.

Lmk what you think, glad you like the fast install and thanks again for raising this issue 🙇

**Comment by lukejacksonn** [comment] 2020-01-16 19:07
Fixed by #35

**Closed by lukejacksonn** 2020-01-16 19:07 UTC
